[package]
name = "willy"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
crossterm = "0.27"
flashkick = { path = "../flashkick"}
indoc = "2"
ratatui = "0.25"
