# Run linters.
name: linting
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Lint
        run: cargo clippy --all-targets --all-features -- -D clippy::all
        continue-on-error: true
      - name: Format
        run: cargo fmt -- --check
