# Runs general build and test logic.
name: testing
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  GUILE_LOAD_PATH: .
  LD_LIBRARY_PATH:  target/debug
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install guile-3.0-dev
      - name: Rust Cache
        uses: Swatinem/rust-cache@v1
      - name: Install Cargo Nextest
        uses: taiki-e/install-action@nextest
      - name: Rust Build
        run: cargo build
      - name: Rust Test
        run: cargo test
      - name: Scheme Build
        run: guild compile sage/core/*.scm sage/*.scm
      - name: Scheme Tests
        run: |
          guile sage/tests/rope-tests.scm
