# Runs general build and test logic.
name: testing
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install guile-3.0-dev
      - name: Install Cargo Nextest
        uses: taiki-e/install-action@nextest
      - name: Rust Cache
        uses: Swatinem/rust-cache@v1
      - name: Build
        run: cargo build --verbose
      - name: Rust Test
        run: cargo nextest run
      - name: Rust Doctest
        run: cargo test --doc
      - name: Scheme Test
        run: |
          find scheme/tests -type f -name "*.scm" -exec cargo run -- {} \; >test-results.txt
          cat test-results.txt
        env:
          GUILE_LOAD_PATH: scheme
      - name: Detailed Scheme Test Results
        run: cat *.log
