# Runs general build and test logic.
name: testing
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  GUILE_LOAD_PATH: scheme
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install guile-3.0-dev
      - name: Rust Cache
        uses: Swatinem/rust-cache@v1
      - name: Rust Build
        run: make build-rust
      - name: Rust Test
        run: make test-rust
      - name: Rust Doctest
        run: make test-rustdoc
      - name: Scheme Build
        run: make build-scheme
      - name: Scheme Test
        run: make test-scheme
      - name: Detailed Scheme Test Results
        run: cat *.log
